/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2012-11-13 17:48:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map.Entry;
import globo.bbb.datastore.Result.PartResult;
import java.util.Date;
import java.util.SortedMap;
import globo.bbb.datastore.CassandraFacade;
import globo.bbb.datastore.Result;
import globo.bbb.util.PerformanceCounters;

public final class resultado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Resultado</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<h1>Indicadores de desempenho do servidor</h1>\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Número requisições cassandra</td>\n");
      out.write("\t\t<td>");
      out.print(PerformanceCounters.getNumCassandraReqs());
      out.write("</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Tempo médio de acesso ao cassandra</td>\n");
      out.write("\t\t<td>");
      out.print(PerformanceCounters.getCassandraAvgReqTime());
      out.write("</td>\n");
      out.write("\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t<td>Número requisições de votos</td>\n");
      out.write("\t\t<td>");
      out.print(PerformanceCounters.getNumVoltes());
      out.write("</td>\n");
      out.write("\t</tr>\n");
      out.write("\t<tr>\n");
      out.write("\t\t<td>Tempo médio de requisição de voto</td>\n");
      out.write("\t\t<td>");
      out.print(PerformanceCounters.getVolteAvgReqTime());
      out.write("</td>\n");
      out.write("\t</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<h1>Resultado da votação</h1>\n");
      out.write("\n");
      out.write("<table border=\"1\">\n");
      out.write("\t<tr><td>Dia-hora</td><td>Participante 1</td><td>Participante 2</td></tr>\n");
      out.write("\n");
      out.write("\t");

		Result result = CassandraFacade.getInstance().GetOfficialResult();
		SortedMap<Date, PartResult> voltes = result.getVoltes();
		long total1 = 0;
		long total2 = 0;
		for(Entry<Date, PartResult> entry : voltes.entrySet())
		{
		  total1 += entry.getValue().getContestant1();
		  total2 += entry.getValue().getContestant2();
	
      out.write("\n");
      out.write("\t\t<tr><td>");
      out.print(entry.getKey().toLocaleString() );
      out.write("</td><td>");
      out.print(entry.getValue().getContestant1());
      out.write("</td><td>");
      out.print(entry.getValue().getContestant2());
      out.write("</td></tr>\n");
      out.write("\t");

		}
	
      out.write("\t\n");
      out.write("\t<tr><td>TOTAL</td><td>");
      out.print(total1);
      out.write("</td><td>");
      out.print(total2);
      out.write("</td></tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
